### ISSUE TITLE
register works but not login

### ISSUE THREAD

**Issue by jsoref** [duo-labs/webauthn#10]
Yubikey w/ Chrome 70 on macOS Mojave:

* I'm able to use https://demo.yubico.com/u2f?tab=register to register and login

Steps:
1. insert yubikey
1. Load https://webauthn.io/
1. enter "test" for the username
1. leave attestation type "none" and authentication type "cross platform"
1. click "register"
1. yubikey flashes
1. tap flashing indicator
1. "You're logged in!"

1. load https://webauthn.io/
1. enter "test" for the username
1. leave attestation type "none" and authentication type "cross platform"
1. click "login with credential"
1. yubikey does not flash
1. the page shows "Logging In..." "Tap your security key to login."
1. a prompt appears "Use your security key with webauthn.io" "Plug in your security key and activate it".
-- my security key is plugged in. it is not flashing
1. I press the button anyway.
1. Nothing happens.

The same behavior happened on Firefox Nightly on Mojave.

Yubikey w/ edge 44.18272.1000.0 on windows 10 1809 / 18272.1000

Steps:
1. insert yubikey
1. Load https://webauthn.io/
1. enter "test" for the username
1. leave attestation type "none" and authentication type "cross platform"
1. click "register"
1. the first time, windows security asked me to create a security pin (pin field twice) all subsequent instances the pin field is listed once
1. yubikey flashes
1. tap flashing indicator
1. "You're logged in!"

1. load https://webauthn.io/
1. enter "test" for the username
1. leave attestation type "none" and authentication type "cross platform"
1. click "login with credential"
1. yubikey does not flash
1. the page shows "Logging In..." "Tap your security key to login." -- briefly
1. it disappears and I'm left with "UnknownError"

**Comment by nicksteele** [comment]
Hey @jsoref Thanks for the alert and apologies for the late response. I'm in the process of refactoring this library to be a standalone webauthn package and then breaking out the website component into a separate repo that uses this package. While we're refactoring the code I will address this issue.

**Comment by nicksteele** [comment]
Hi @jsoref this should be solved in the new refactor of the project, please reach out if you have any questions!
