### ISSUE TITLE
Support for Second Factor Flow?

### ISSUE THREAD

**Issue by briansboyd** [duo-labs/webauthn#11]
Hi!  
Our first use of FIDO2 and WebAuthn will use the 2FA flow.  I am able to Register via 2FA (requireResidentKey=false) but am not able to 'Login' (login meaning, I'm assuming, that simply the second factor is authenticated).  I'm using U2F compatible Yubikey 4 series.  Shoud this work?

I am able to use 2FA at https://webauthndemo.appspot.com/Home.  Is there an issue authenticating using localhost?

Thanks,
Brian

**Comment by nicksteele** [comment]
Hi @briansboyd and sorry for the late reply, we just got finished refactoring this library. The Yubikey 4 should be able to support the `fido-u2f` attestation type and you shouldn't have an issue authenticating to local. Some browser implementations have/had an issue discerning localhost as a valid RP URI, but this may be solved by using `0.0.0.0` instead.
