### ISSUE TITLE
Project maintained?

### ISSUE THREAD

**Issue by jgimenez** [duo-labs/webauthn#112]
I see this project has several good PRs waiting to be merged, including security updates.

Is this project still maintained? If not, it might be better to mark it as read-only, so people know they must move on. Looking at the project "Network" graph, I see a fork from authelia that has several of these PRs merged.

**Comment by davedoesdev** [comment]
Agreed, especially with a security-related project it's important to know update policy.

**Comment by davedoesdev** [comment]
It seems this project has a new maintainer now (see https://github.com/duo-labs/webauthn/pull/101)

**Comment by MasterKale** [comment]
Hello all, I do indeed have write access to this project now but, while **py_webauthn** is my baby now, here I'm a simple button clicker. I'm relying on a few maintainers I know personally (specifically @nicksteele and @aseigler) and others who've contributed before to help me identify which things to merge.

If someone wants to triage the remaining PR's and let me know which to merge and which to close I'll take care of it.

**Comment by james-d-elliott** [comment]
I think of the ones remaining the one I'd be confident in saying is ready is #80. I added a test to demonstrate it, if you're unsure of how to run the test I can help you with that either in the PR itself or via one of the chat systems I've got in my Bio/Profile. I think it should make sense though due to your background with py_webauthn.

**Comment by Jmayorgagx13** [comment]
> I see this project has several good PRs waiting to be merged, including security updates.
> 
> 
> 
> Is this project still maintained? If not, it might be better to mark it as read-only, so people know they must move on. Looking at the project "Network" graph, I see a fork from authelia that has several of these PRs merged.

Help how to have PRS merge
