### ISSUE TITLE
RPOrigin is validated exactly against the url's fully qualified host name leaving no room for other use cases.

### ISSUE THREAD

**Issue by igmor** [duo-labs/webauthn#143]
There's a use case where a user performs the WebAuthn registration or verification at sub.domain.com, some portal page, then there are some redirects until the resultant WebAuthn data hits auth.domain.com. This is where the actual RP verification happens, and at this point, the origin validation would fail, because the RP expects an origin of auth.domain.com from the request context, whereas the actual WebAuthn request was performed at sub.domain.com.

Here is how it is implemented:
https://github.com/duo-labs/webauthn/blob/4d1cf2d3405194e18bbcaa654485927e9a985707/protocol/client.go#L93

Another use case might be some FIDO2 SAMLv2 proxy, where a single entity would authenticate users via webauthn protocol and then would redirect a request to a saml validation endpoint.  

Here is how it is implemented in alternative libraries, note there is a list of preconfigured RP Origins

https://github.com/webauthn4j/webauthn4j/blob/b3f67afb94dc4187b7b01b4e593c8560841f27c0/webauthn4j-core/src/main/java/com/webauthn4j/validator/OriginValidatorImpl.java#L56

**Comment by maxwelmunthe27** [comment]
I got the same issue too

**Comment by arianvp** [comment]
Would it be possible for you to set your RPID to `domain.com`  when initating the flow on `auth.domain.com` ?  then `sub.domain.com` will be able to verify the assertion just fine as `sub.domain.com` is a valid origin for the `domain.com` rpId

> By default, the [RP ID](https://www.w3.org/TR/webauthn-2/#rp-id) for a WebAuthn operation is set to the caller’s [origin](https://html.spec.whatwg.org/multipage/webappapis.html#concept-settings-object-origin)'s [effective domain](https://html.spec.whatwg.org/multipage/origin.html#concept-origin-effective-domain). This default MAY be overridden by the caller, as long as the caller-specified [RP ID](https://www.w3.org/TR/webauthn-2/#rp-id) value [is a registrable domain suffix of or is equal to](https://html.spec.whatwg.org/multipage/origin.html#is-a-registrable-domain-suffix-of-or-is-equal-to) the caller’s [origin](https://html.spec.whatwg.org/multipage/webappapis.html#concept-settings-object-origin)'s [effective domain](https://html.spec.whatwg.org/multipage/origin.html#concept-origin-effective-domain).

**Comment by MasterKale** [comment]
Support for multiple origins is also in the two libraries I wrote:

- https://github.com/MasterKale/SimpleWebAuthn/pull/91
- https://github.com/duo-labs/py_webauthn/blob/master/webauthn/authentication/verify_authentication_response.py#L48

It's a common enough scenario in more complex RPs that I think this library should implement similar functionality.

**Comment by igmor** [comment]
yeah scoping roprigin to a general domain would work for some use cases. I was also looking into supporting the list of unrelated domains.
