### ISSUE TITLE
How does navigator.credentials.create interact with the authenticator?

### ISSUE THREAD

**Issue by holycleugh** [duo-labs/webauthn#15]
The WebAuthn spec says

>Clients can communicate with authenticators using a variety of mechanisms. For example, a client MAY use a client device-specific API to communicate with an authenticator which is physically bound to a client device. On the other hand, a client can use a variety of standardized cross-platform transport protocols such as Bluetooth (see §5.10.4 Authenticator Transport Enumeration (enum AuthenticatorTransport)) to discover and communicate with cross-platform attached authenticators. 

I don't understand exactly *how* this works though. My understanding is, the Relying Party's JavaScript executes `navigator.credentials.create` in the user agent. How does the browser know what authenticator to use (whether it's bluetooth, nfc, etc.)? What if there are multiple bluetooth devices available? Does the browser itself perform the connection over a web api?

Does the authenticator need to be "installed" or registered in some way into the web browser via an add-on? If I wanted to just use another operating system process as the authenticator, as I think in this example, what would be the communication method between the browser's JS and the external process?

**Comment by nicksteele** [comment]
Hi @holycleugh, it is my understanding that the browser is able to handle WebAuthn requests by discovering and calling out to platform and cross-platform devices that broadcast themselves. USB HID devices, like Yubikeys, can communicate with browsers, but this area is not really my forté. Check out the [FIDO Chromium Library](https://cs.chromium.org/chromium/src/device/fido/README.md) that Chrome uses to handle HID and BLE devices to see how this works. 

The authenticator does not need to be installed or registered, if it is discoverable by the browser, like a HID, it can be used without an add-on. If you wanted to use an OS process, it would have to be registered/emulated as a HID device. I would check out [Github's SoftU2F repo](https://github.com/github/SoftU2F) for an example.

**Comment by holycleugh** [comment]
Thank you for the reference, it was very helpful. Would you happen to know how this would work on mobile (a mobile app granting permissions to a mobile web browser)? Or if not, where could I ask such a question?

**Comment by aseigler** [comment]
Here is the current draft specification for the client to authenticator protocol: https://fidoalliance.org/specs/fido-v2.0-rd-20180702/fido-client-to-authenticator-protocol-v2.0-rd-20180702.html

It works exactly the same on a mobile device as it does on a desktop or laptop.  This page explains some of it fairly well: https://techcommunity.microsoft.com/t5/Identity-Standards-Blog/All-about-FIDO2-CTAP2-and-WebAuthn/ba-p/288910

**Comment by holycleugh** [comment]
Thank you @aseigler. I'm wondering about the specifics of roaming authenticator discovery on mobile browsers, in the case the authenticator is a mobile app on the same device. It appears that phones cannot connect to themselves over bluetooth. Would NFC work?

**Comment by holycleugh** [comment]
All right, thanks for the resources.
