### ISSUE TITLE
Inquiry regarding the use of test data.

### ISSUE THREAD

**Issue by kj84park** [duo-labs/webauthn#153]
Hello, I would like to politely ask if your test data can be used for some of our test cases (https://github.com/line/line-fido2-server). I already know it's a BSD-3 license, but I still wanted to ask.

https://github.com/duo-labs/webauthn/blob/00c9fb5711f57e43becab7ef8dd6551180ef883a/protocol/attestation_tpm_test.go#L33-L34

**Comment by aseigler** [comment]
Absolutely, please proceed.

**Comment by kj84park** [comment]
@aseigler  Yes, I will. Thank you for your quick reply!
