### ISSUE TITLE
README typo RPID-->RPIcon

### ISSUE THREAD

**Issue by zeidlermicha** [duo-labs/webauthn#16]
Hey Guys,

I've just noticed that in the README there is a small typo.
Under https://github.com/duo-labs/webauthn#initialize-the-request-handler in the example, there is RPID twice, instead of RPID and RPIcon.
it should be:
```
func main() {
    web = webauthn.New(&webauthn.Config{
        RPDisplayName: "Duo Labs", // Display Name for your site
        RPID: "duo.com", // Generally the FQDN for your site
        RPOrigin: "https://login.duo.com", // The origin URL for WebAuthn requests
        RPIcon: "https://duo.com/logo.png", // Optional icon URL for your site
    })
```

**Comment by nicksteele** [comment]
Thanks for the heads up @zeidlermicha I'll fix this right now
