### ISSUE TITLE
Option to allow all authenticator types

### ISSUE THREAD

**Issue by slokhorst** [duo-labs/webauthn#17]
Currently, WebAuthn.io requires the user to select an authentictor type. However, as I understand from the spec, `authenticatorSelection` is an optional field when creating the credentials.

Wouldn't it make sense to also provide a third "either" Authenticator Type option on WebAuthn.io? I guess this would also be useful in real-world applications, where I don't really care if the user has a platform authenticator or a roaming authenticator. In the end the user is always responsible for keeping their private key secure, whether it is on device or on an external.

It would also be useful to demonstrate how browsers present the choice between platform and roaming authenticators in case the user has both.

**Comment by aseigler** [comment]
This issue belongs over in the [WebAuthn.io](https://github.com/duo-labs/webauthn.io) repo.  This one is for the library. 

Fixing this should be as easy as adding a default "Unspecified" option and then ensuring that null value handling works as expected.

**Comment by nicksteele** [comment]
as mentioned this is an issue for the demo site [`webauthn-io`] repo, (https://github.com/duo-labs/webauthn.io). I've [transferred this issue](https://github.com/duo-labs/webauthn.io/issues/1)
