### ISSUE TITLE
works for Desktop and Mobile apps ?

### ISSUE THREAD

**Issue by gedw99** [duo-labs/webauthn#26]
I tested the server with my yubikey and chrome on your demo website and works great. thanks for this.

But what about Desktop Apps and Mobile Apps ? 

I want to enable my desktop and mobile apps ( i write them in flutter, but use golang with them ) to also use a yubikey.

**Comment by aseigler** [comment]
This is a server library.  If you are looking for a client library, check out this list: https://github.com/herrjemand/awesome-webauthn#client-libs

There are some excellent examples there for a variety of use cases.

**Comment by nicksteele** [comment]
We have an [Android library available here](https://github.com/duo-labs/android-webauthn-authenticator) as a resource for handling the WebAuthn protocol on Android mobile devices and the list Alex mentioned also has some great libraries as well. I'm not sure of any desktop app specific resources, but will reach out if I see one!
