### ISSUE TITLE
please provide minimal working example

### ISSUE THREAD

**Issue by trusch** [duo-labs/webauthn#27]
I like to use webauthn.io as reference implementation, but its quiet specific in some cases, especially the frontend is not really minimal (using jquery etc.)

It would be nice to have a minimal working example to compare the own implementation against.

Due to the fact that the standard is not very old the error handling in chrome is not very nice, and I only get a DomException whenever I try to navigator.credentials.create(). With a minimal example I could at least compare my options and the the options from the reference implementation.

**Comment by k-spit** [comment]
I would join the previous speaker. A minimal example would be extremely helpful.

**Comment by aseigler** [comment]
I would suggest taking a look at the previous version at https://github.com/duo-labs/webauthn/tree/webauthn.io-refactor. It's nowhere near as pretty but it's straightforward and concise.

**Comment by hbolimovsky** [comment]
I made a pretty minimal/basic webauthn client and server using this library: https://github.com/hbolimovsky/webauthn-example, as well as an accompanying blog post: https://www.herbie.dev/blog/webauthn-basic-web-client-server/

**Comment by nicksteele** [comment]
Thanks @hbolimovsky, this is great! Could I link to this in the README?

**Comment by hbolimovsky** [comment]
@nicksteele absolutely!

**Comment by nicksteele** [comment]
Added link to the README
