### ISSUE TITLE
inconsistency between devices / hostnames

### ISSUE THREAD

**Issue by gnur** [duo-labs/webauthn#29]
I'm using this library to add webauthn to a pet project. On my test domain, it was working just fine. I can register both my macbook pro (2017) and my phone (galaxy s9+), when I deploy it to my "production" environment, I can register my macbook, but I cannot register my phone.

When I try to register my phone I get the following error:

`Error finding cert issued to correct hostname: x509: certificate signed by unknown authority`.

Test domain is similar to: `tst.tmp.example.nl`,
production domain is similar to: `prod.example.xyz`.

Is there any reason why a different end point would not be allowed?

**Comment by aseigler** [comment]
This sounds like an SSL cert configuration issue (cert not trusted by phone) on the web server, not a library configuring thing.  The only thing in the library that would be in play here is the config.RPOrigin, which must be set appropriately or your browser will throw a security error in navigator.credentials.create.  You don't seem to be getting to that point.

**Comment by gnur** [comment]
Well, the error is generated here: https://github.com/duo-labs/webauthn/blob/master/protocol/attestation_safetynet.go#L83

Which specifically mentions `attest.android.com`, it sounds like something that I do not control by hosting it on a different domain.
Both test and prod environment use letsencrypt certificates.

**Comment by aseigler** [comment]
Ahhh, yes, my bad.  Definitely not an SSL thing.  Interesting, I haven't seen this one myself.

**Comment by nicksteele** [comment]
I think this is SafetyNet/device issue since Chrome Android defaults to using SafetyNet attestation instead of `packed` or `fido-u2f` now. I haven't seen this issue on my Pixel 3 and will try to duplicate this with a Galaxy S9 emulator.

**Comment by aseigler** [comment]
Chrome on my Android is definitely defaulting to SafetyNet, and I'm not seeing this issue.

**Comment by gnur** [comment]
It looks like it is related to the fact that I have some progressive web app stuff in there, using `yarn serve` it works, using the files built by `yarn build` do not.

I'm gonna make a test matrix and test all variables I have found so far and see if I can find a clear cause.

**Comment by nicksteele** [comment]
Thanks!

**Comment by gnur** [comment]
It turns out the issue was non-related. The culprit was not having `ca-certificates` installed in my docker image.
