### ISSUE TITLE
signature verification for basic attestation broken

### ISSUE THREAD

**Issue by pschultz** [duo-labs/webauthn#31]
`handleBasicAttestation` attempts to convert a COSE algorithm identifier (`alg` in the code below) to x509.SignatureAlgorithm (unless the device seems to be a YubiKey).

These values obviously don't align, so all verifications fail with

> x509: cannot verify signature: algorithm unimplemented

https://github.com/duo-labs/webauthn/blob/1500f40bdab7800964d135283af03fab3a3c46c0/protocol/attestation_packed.go#L92-L96

This code should map the COSE ID to [one of the x509 constants](https://golang.org/pkg/crypto/x509/#SignatureAlgorithm) instead.

grep shows similar code in attestation_tpm.go and attestation_androidkey.go.

**Comment by aseigler** [comment]
I ran into this as well and fixed the case I found in #28.

**Comment by aseigler** [comment]
This should be fixed by #33. Can you confirm?

**Comment by pschultz** [comment]
@aseigler, I can confirm that it works for the "packed" format now, but it looks like the code for "android-key" and "tpm" hasn't been fixed.

**Comment by aseigler** [comment]
OK. TPM is definitely fine, it follows a different path even though it appears similar on the surface. I can't test Android Key yet, it may still be broken.

**Comment by pschultz** [comment]
I'm not in a position to test the Android format either, unfortunately.

**Comment by aseigler** [comment]
Me neither, blocked by https://github.com/fido-alliance/conformance-tools-issues/issues/438 still.
