### ISSUE TITLE
Unsupported Public Key Type after upgrading webauthn

### ISSUE THREAD

**Issue by artooro** [duo-labs/webauthn#41]
We were using version `v0.0.0-20190206165356-8065b78cf2cb` of this webauthn library for our initial Webauthn support. And recently tried updating to the latest version which at this point is `v0.0.0-20190521121529-2fa2ec45d1eb` (based on versions in go.mod)

After updating, all existing user keys that we've stored are no longer working, and the error we are seeing in the logs is:

```
Error validating the assertion signature: Unsupported Public Key Type
```

I've been reading through the changes made to protocol/assertion.go but have not been able to determine what the incompatibility is.
If I save the keys using the latest version of the library it works fine without changing any of our code.

Hoping you guys have some ideas on what I can do.

**Comment by aseigler** [comment]
Prior to #20, credential public keys were stored on a pre-parsed format that would only support EC keys. Afterward, credential public keys are stored raw, just as the browser submits them to the server. This allows support for all key types, including key types that could be added to the spec in the future. As a result though, existing stored parsed keys won't parse correctly as the new reader is expecting raw credential public keys.

**Comment by artooro** [comment]
Thanks @aseigler -- I'll see if I can figure out how to convert the pre-parsed data to raw for all existing users. If you have a pointer on how to do that it'd be awesome. If not I'll comment here how I did it.

**Comment by aseigler** [comment]
It shouldn't be too hard, take a look a PublicKeyData vs EC2PublicKeyData structs from #20. All old PublicKeyData should map to new EC2PublicKeyData.

**Comment by artooro** [comment]
Here's the code that I wrote (removed error handling to simplify) to convert our existing stored public keys into the new raw format.

``` go
// Decode existing stored public key
pemBlock, _ := pem.Decode(storedPublicKey)
parsedKey, _ := x509.ParsePKIXPublicKey(pemBlock.Bytes)
publicKey := parsedKey.(*ecdsa.PublicKey)

// Map into EC2PublicKeyData
publicKeyData := webauthncose.EC2PublicKeyData{
  PublicKeyData: webauthncose.PublicKeyData{
    KeyType:   2,
    Algorithm: -7,
  },
  XCoord: publicKey.X.Bytes(),
  YCoord: publicKey.Y.Bytes(),
  Curve:  publicKey.Params().B.Int64(),
}

// Encode to raw format based on webauthn spec
var cborHandler codec.Handle = new(codec.CborHandle)
var publicKeyRaw []byte
e := codec.NewEncoderBytes(&publicKeyRaw, cborHandler)
e.Encode(publicKeyData)

// publicKeyRaw is the new value that can be stored to be compatible going forward
```
