### ISSUE TITLE
navigator.credentials.get() option to suppress chrome UI popup if allowCredentials in not present in the authenticator 

### ISSUE THREAD

**Issue by kmlhossen** [duo-labs/webauthn#42]
I was playing with this implementation in the chrome with mac inbuilt fingerprint scanner and wondering what will be the solution to this kind of flow for a relying party.

1. Let's say user registered webauthn in device **A** with the relying party **R**. 
Authentication flow is like this, the user comes to the relying party **R** input username and clicks next, relying party pulls the previously registered credential Ids for the user to create allowCredentials and query the authenticator for authentication. All goes fine as authenticator has one of those allowCredentials associated private key

2. But let's say the same user goes to the device **B** and tries to login with the same relying party **R** by putting username and clicking next. This time again the relying party pulls over the registered credential Ids for the user to create allowCredentials and query the authenticator for authentication. But this time as the device **B** does not have any associated private key it shows an error popup window in chrome.

Is there any way we can pass any option to the **navigator.credentials.get** call so that if the associated private key is not present for the given allowCredentials we can just stop the webauthn flow and fall back to some other authentication method without showing the error popup window.

**Comment by aseigler** [comment]
This sounds like a client side thing you might be able to work out in JavaScript maybe?  I'm not sure if what you are talking about is even possible, but it certainly doesn't seem like a library issue.

**Comment by nicksteele** [comment]
I don't believe this is a library issue either, although you may want to bring this up with the W3C group.
