### ISSUE TITLE
Ambiguous import for ugorji/go/codec

### ISSUE THREAD

**Issue by hdm** [duo-labs/webauthn#44]
Importing this module can lead to the following error:
```
build github.com/hdm/thing: cannot load github.com/ugorji/go/codec: ambiguous import: found github.com/ugorji/go/codec in multiple modules:
        github.com/ugorji/go v1.1.4 (C:\Users\Developer\go\pkg\mod\github.com\ugorji\go@v1.1.4\codec)
        github.com/ugorji/go/codec v0.0.0-20190204201341-e444a5086c43 (C:\Users\Developer\go\pkg\mod\github.com\ugorji\go\codec@v0.0.0-20190204201341-e444a5086c43
```

A quick fix is adding the following to go.mod:
`replace github.com/ugorji/go => github.com/ugorji/go/codec v1.1.7`

The specific import is `github.com/duo-labs/webauthn@v0.0.0-20190712160819-dbd86f4e9d66 github.com/ugorji/go/codec@v0.0.0-20190204201341-e444a5086c43`

This might be fixed by upgrading the dependency on `codec` to v1.1.7 in this module.

**Comment by jordan-wright** [comment]
Thanks for the heads up @hdm! We'll get this fixed ASAP.

**Comment by nicksteele** [comment]
Thanks @hdm for the issue, this should now be resolved!

**Comment by hdm** [comment]
Thanks!
