### ISSUE TITLE
How to distinguish between 2FA and passwordless login?

### ISSUE THREAD

**Issue by arianvp** [duo-labs/webauthn#49]
How do I make sure that only a FIDO2 key is used, both on the client and the server?   From the spec I see that passwordless login should only be supported for FIDO2 keys, but the `webauthn.io` demo seems to work fine with U2F too. Which sounds odd as it isn't recommended to use U2F keys for passwordless login

From what I understand from the spec, if you log in with a U2F device instead of a FIDO2 device, the security key will not set the `userHandle`  as it doesn't keep track of it. My idea was to decide on the presence of `userHandle` whether this is a second factor or a passwordless login.   However, the `webauthn` library doesn't expose this attribute to the enduser in `FinishRegistration`

Is there a way for the server to make sure that the client who initiated the login indeed used a FIDO2 device, and thus it is safe to do a passwordless login?

Also (but not related to this code per se) can I force the client to make sure only FIDO2 keys work when calling `register` or `create` ?

**Comment by arianvp** [comment]
I think ResidentKeyRequired is what I am looking for, but this is currently hardcoded to always be `false` during registration, which I think is wrong. It should be an argument to `BeginRegstration` no?

https://github.com/duo-labs/webauthn/blob/091e78d924b5f6fbaace0f6af53a783d118d3807/webauthn/registration.go#L44

**Comment by arianvp** [comment]
Update : Aha I can override the authenticator selection!

I guess I need this:

https://github.com/duo-labs/webauthn/blob/910a8cce875b2459c287e51d7f1882f7847a275b/webauthn/authenticator.go#L24


and this https://github.com/duo-labs/webauthn/blob/091e78d924b5f6fbaace0f6af53a783d118d3807/webauthn/registration.go#L78

to implement this?

**Comment by arianvp** [comment]
I think I have asnwered my own question now, by looking at another implementation's docs:

https://github.com/Yubico/java-webauthn-server/blob/c14b91e6fcfd70d6caf1d05fac241f461230a9e4/webauthn-server-core/src/main/java/com/yubico/webauthn/package-info.java#L153-L160

For registration, indeed setting `requireResidentKey` is useful.  To let the FIDO device prove that it indeed has a resident key, during login, make the `allowedCredentials` list _empty_.  If the device is not FIDO2 then the login will fail, as it has no idea how to choose the public key.

**Comment by nicksteele** [comment]
Hey arianvp and apologies for the late reply. 2FA logins should be distinguishable from FIDO2/WebAuthn in the case where they require attestation and/or user verifications. U2F requests can be retroactively supported using the `AppID` extension, however are incapable of performing user verification like newer FIDO2 authenticators.
