### ISSUE TITLE
pubKeyCredParams should be required, not optional?

### ISSUE THREAD

**Issue by arianvp** [duo-labs/webauthn#54]
I've been reading the spec https://www.w3.org/TR/webauthn/#dictdef-publickeycredentialcreationoptions

and nothing from it seems to suggest that `pubKeyCredParams` is optional. Indeed, it seems to be a required property for registration (as opposed to e.g. `excludeCredentials` which is optional and defaults to empty if it isn't given).

Is the real world inconsistent with the spec in this case; or what is going on exactly?

**Comment by nicksteele** [comment]
The `pubKeyCredParams` should be required for registration and conditionally optional for assertion

**Comment by arianvp** [comment]
Aha I see. thanks! that makes sense
