### ISSUE TITLE
Do not accept null/empty rpid. as the specification states supported.

### ISSUE THREAD

**Issue by slayercat** [duo-labs/webauthn#61]
the [spec](https://w3c.github.io/webauthn/#GetAssn-DetermineRpId) said：
```
If options.rpId is not present, then set rpId to effectiveDomain.
Otherwise:

If options.rpId is not a registrable domain suffix of and is not equal to effectiveDomain, return a DOMException whose name is "SecurityError", and terminate this algorithm.

Set rpId to options.rpId.

Note: rpId represents the caller’s RP ID. The RP ID defaults to being the caller’s origin's effective domain unless the caller has explicitly set options.rpId when calling get().
```

But we could not set it to empty / null.

This is useful when webauthn rpid could not be pre-assigned.  such as in LAN-local application which accessed by ip address.

**Comment by slayercat** [comment]
This could workaround by asking the webpage to pass url accessing to the server. but it's still frowned.

**Comment by nicksteele** [comment]
The specification does not require the rpID to be set and IP addresses are not supported by the standard, although I know you have an ongoing ticket. Please feel free to reopen this if this is changed in the standard.
