### ISSUE TITLE
Compiling to JavaScript

### ISSUE THREAD

**Issue by pulsejet** [duo-labs/webauthn#65]
I managed to compile this library to JS (described in [this blog post](https://medium.com/@varunpp2/a-js-webauthn-server-running-in-the-browser-written-in-go-143f672ad085)) with GopherJS with a smalll wrapper and [a few changes](https://github.com/pulsejet/webauthn/commits/master):
1) fxamacker/cbor instead of ugorji/go/codec - the latter is bloat, and doesn't play well with GopherJS
2) Removed net/http dependency by getting rid of cfssl and breaking some stuff in metadata. This isn't necessary, but reduces the bundle size to half, and wouldn't work anyway if I understand correctly.

Just wanted to know if there is any chance the first change could be incorporated in this repo, so keeping in sync will be easier.

**Comment by pulsejet** [comment]
This will also fix #66

**Comment by davedoesdev** [comment]
Following @pulsejet 's lead, I'm using a Web Assembly version of this library in my Node.js module: https://github.com/davedoesdev/webauthn4js
