### ISSUE TITLE
local golang webauthn.io: Error Validating Origin on update

### ISSUE THREAD

**Issue by jchax** [duo-labs/webauthn#72]
Start with `git clone https://github.com/duo-labs/webauthn.io.git` and golang 1.14.3 and use this config.json:
```
{
    "db_name": "sqlite3",
    "db_path": "webauthn.db",
    "host_address": "127.0.0.1",
    "host_port": "9005",
    "relying_party": "localhost"
}
```

All goes swimmingly.   I can register a use and log in.

`go get -u ./...` doesn't work for unrelated (and presumably fixable, somewhere, reasons, so removing go.mod and go.sum and re-creating them with `go mod init github.com/duo-labs/webauthn.io` and then building produces a server that doesn't work -- registration appears to be successful (from the browser) but the server reports "error validating origin" and login either with the previous registered user or a new user fails.

At least that's what it did last night.  Today it's just hanging in the registration process.  It's not just the webauthn.io demo, of course, other apps using the webauthn code also fail.

The working version from go.mod is
	github.com/duo-labs/webauthn v0.0.0-20191119193225-4bf9a0f776d4

**Comment by jchax** [comment]
The problem is the construction of a default RPOrigin.   If I explicitly set it to `http://localhost:9005 `(as below) then both the old version and v0.0.0-20200408163612-425dee8942f4 work.   Both the protocol and the port need to be specified.  If it's the default port (80, in this case) then you have to use `http://localhost`.

The patch below isn't the fix: that should probably be in webauthn.New to construct a correct RPOrigin.

Hope that helps.   If you want me to test a possible fix, please don't hesitate to ask.

```
diff --git a/server/server.go b/server/server.go
index 826a73b00b89..46a421e9cb64 100644
--- a/server/server.go
+++ b/server/server.go
@@ -46,6 +46,7 @@ func NewServer(config *config.Config, opts ...Option) (*Server, error) {
        defaultWebAuthn, _ := webauthn.New(&webauthn.Config{
                RPDisplayName: config.RelyingParty,
                RPID:          config.RelyingParty,
+               RPOrigin:      "http://" + config.RelyingParty + ":" + config.HostPort,
        })
        ws := &Server{
                config:   config,
```

**Comment by nicksteele** [comment]
Hey @jchax sorry for the late reply on this. This may have been fixed in a recent update, do you know if this is still an issue for you? Any possible fixes would be much appreciated :)
