### ISSUE TITLE
macOS Chrome Canary supports TPM for creations but not login

### ISSUE THREAD

**Issue by eldridgea** [duo-labs/webauthn#9]
On macOS 10.13.16 using Chrome Canary 71.0.3558.0, I can create an account using the Macbook Pro fingerprint scanner by slecting the TPM option, however I cannot login the same way. 

When attempting to do so the macOS systemdialog prompting for a fingerprint does not appear and my Yubikey begins flashing the same as if I had selected "cross platform" as my authentication type.

**Comment by slokhorst** [comment]
Should be working in the stable Chrome 70 according to https://www.chromestatus.com/feature/5962264427364352 . Don't have a Touch ID Mac myself to confirm unfortunately.

**Comment by nicksteele** [comment]
This should now be handled in Chrome and Canary builds
