### ISSUE TITLE
Verify "alg" parameter

### ISSUE THREAD

**Issue by DanielSanchezDiaz** [duo-labs/webauthn#94]
Hi all! Your library has been very helpful to me in understanding webauthn. I've been trying to implement webauthn as well as make sure all the steps for registering a credential are followed ("https://www.w3.org/TR/webauthn/#sctn-registering-a-new-credential"). Currently I am on step 16 "Verify that the "alg" parameter in the credential public key in authData matches the alg attribute of one of the items in options.pubKeyCredParams." I am having difficulty getting the "alg" parameter in credential public key. I noticed that in protocol/authenticator.go:46 that the credential public key is kept as bytes and not given a struct with fields. Should CredentialPublicKey have a corresponding struct?
I also noticed that the "alg" parameter in attestation statements is used for verification, such as in attestation_packed.go. Does this do what I am trying to do?
Thanks so much! :)

**Comment by aseigler** [comment]
Check PublicKeyData struct protocol/webauthncose/webauthncose.go:27 and the rest of what's going on in that file, I think that will get you what you're looking for.

**Comment by DanielSanchezDiaz** [comment]
> Check PublicKeyData struct protocol/webauthncose/webauthncose.go:27 and the rest of what's going on in that file, I think that will get you what you're looking for.
Awesome! Thanks so much!
