### ISSUE TITLE
AAGUID is always zero'd out during registration and authentication

### ISSUE THREAD

**Issue by zfLQ2qx2** [duo-labs/webauthn#96]
I am using a YubiKey 5c with the webauth.io demo app, I am requesting direct attestation, however the AAGUID field is always zero'd out. The expected value is ee882879-721c-4913-9775-3dfcce97072a per https://support.yubico.com/hc/en-us/articles/360016648959-YubiKey-Hardware-FIDO2-AAGUIDs

I'm not sure if this is a bug or if I am going something incorrectly.

**Comment by zfLQ2qx2** [comment]
I figured out what https://webauthn.me/debugger was doing differently, they had userVerification set to "preferred" by default and that results in AAGUID being populated instead of all zeros. It looks like the AAGUID id is also present in the certificate that the yubikey sends, so that is where I saw it in the raw data.

**Comment by Infinisil** [comment]
I also ran into this, turns out that Firefox just doesn't implement CTAP2 yet, which is apparently needed for the aaguid to be set. The bug that tracks this is https://bugzilla.mozilla.org/show_bug.cgi?id=1530370

**Comment by james-d-elliott** [comment]
This is controlled by the protocol.ConveyancePreference, if set to direct it will require the AAGUID is sent or it will reject the attestation. I've personally tested this in Firefox and it seems to function. That being said as pointed out by Arian, if the attestation format is `fido-u2f` then it's expected all zeroes, as CTAP1 has no concept of AAGUID (see step 4):

https://fidoalliance.org/specs/fido-v2.0-ps-20190130/fido-client-to-authenticator-protocol-v2.0-ps-20190130.html#u2f-authenticatorMakeCredential-interoperability
